### ISSUE TITLE
Add support for "Makefile" files

### ISSUE THREAD

**Issue by listx** [jcsalomon/smarttabs#29]
I think Makefiles are the perfect candidates for smart tabs, because you *must* insert tabs for describing build rules (at least in GNU Make). Has anyone gotten smart tabs to work with Makefiles?

**Comment by baby-gnu** [comment]
I personally use `align-regexp` for this:

* Select a region
* `M-x` `align-regexp`
* `:=`
* `RET`

I see this more as a graphical beauty than semantic use of tabs, so I think it's not something for smarttabs.

Regards.
