### ISSUE TITLE
To long line causes smart tabs fail

### ISSUE THREAD

**Issue by chep** [jcsalomon/smarttabs#38]
Start emacs -q
Load smart tabs (for me M-x load-file ~/.emacs.d/elpa/smart-tabs..../smart-tabs-mode.elc
Enable it M-: (smart-tabs-insinuate 'c 'c++ 'java 'javascript 'cperl 'python 'ruby 'nxml)
Visit /tmp/test.cpp
Add this code:
# include <iostream>

int main()
{
    int plop(function123456789(first, second);
    return 0;
}

if you press enter after "first,", "second" will be aligned as it should be:
|->int plop(function123456789(first,
|->........................................ second);

If you add numbers (or any characters) to the name of the function, smart tabs fails:
|->int plop(function1234567891011121314151617181920212223242526272829303(first,
|->|->second);

It's ok with:
function123456789101112131415161718192021222324252627282930
And not with:
function1234567891011121314151617181920212223242526272829303

**Comment by zakkak** [comment]
It has to do with the value of `fill-column`. For instance, setting it to 500 it aligns your example correctly.

**Comment by chep** [comment]
That's right, thank you
