### ISSUE TITLE
It doesn't work anymore (at least for c-mode)?

### ISSUE THREAD

**Issue by KrullKorg** [jcsalomon/smarttabs#45]
for some time smarttabs doesn't work anymore; i have emacs 25.1.1
i install smarttabs via use-package
`(use-package smart-tabs-mode
  :ensure t
  :config
  (smart-tabs-insinuate 'c))`
i got only tab-only indentation in c-mode
i'm a noob of emacs so: tell me what info i can provide to help
thanks in advance

**Comment by robohack** [comment]
I'm now running GNU Emacs 25.2 and have recently run 25.1, and I've been using smart-tabs 1.0 with both without any problems.

You can try toggling it off (and maybe on again) by running `smart-tabs-mode` in any buffer visiting a c-mode file (type `<ESC>xsmart-tabs-mode<RETURN>`), and that should help confirm that it is indeed enabled for that buffer (a message should be displayed that will tell if the command had enabled or disabled smart-tabs-mode -- run it again if it was disabled).

I have the following in my `~/.emacs` to automatically enable it (after having installed it with the package manager):

    (progn
      (autoload 'smart-tabs-mode "smart-tabs-mode"
        "Intelligently indent with tabs, align with spaces!")
      (autoload 'smart-tabs-mode-enable "smart-tabs-mode")
      (autoload 'smart-tabs-advice "smart-tabs-mode")
      (autoload 'smart-tabs-insinuate "smart-tabs-mode")
      (smart-tabs-insinuate 'c 'c++ 'java 'javascript 'cperl 'python 'ruby 'nxml))

The autoloads are kind of pedantic -- they could all be replaced by `(require 'smart-tabs-mode)` given that I immediately invoke one of the functions to hook it into other modes; especially given the above expression is all wrapped in yet another which detects whether it has been installed in the loadpath or not.

**Comment by KrullKorg** [comment]
in fact i had already tried: i found that smart-tabs is disabled after opening a c file; with C-h v major-mode i see that i'm in c-mode; using M-x describe-mode i see that the major mode is called "C/l" (and i don't see smart-tabs listed in minor-modes)

i tried to "manually" enable smart-tabs but it didn't work anyway, but after i can see it using M-x describe-mode

i have the same problem under gnu/linux and under windows, same .emacs file

ASAP i'll try to use a "cleaned" .emacs file, to see if there's some conflict

**Comment by jcsalomon** [comment]
@KrullKorg, did using a clean .emacs file solve the problem? I’m curious what the conflict was.

**Comment by KrullKorg** [comment]
yes, i tried yesterday (and now i just made a further test at work) and i found 2 syntax error in my .emacs (not related to smarttabs, http://saetta.ns0.it/gitweb?p=msys2;a=blobdiff;f=tools/emacs_cross;h=77e6d3efe2a2e09aae74bbe7321987aab7121728;hp=0b854d4fbd0772a6f3c74923ece053585a45c6a3;hb=fd7863ee0f84d715c0227961442137baed4ae6eb;hpb=d1668170cb145e827e3dad0258d5a7ecadcf4283); and now smarttabs works again!!! thanks
