### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by mavit** [jcsalomon/smarttabs#48]
MELPA Stable [currently distributes](https://stable.melpa.org/#/smart-tabs-mode) `smart-tabs-mode` version 1.0, from 2013.  Is it time to tag 1.1?

**Comment by hexmode** [comment]
do it.

**Comment by jcsalomon** [comment]
Is anything needed beyond the version bump in Github?

**Comment by mavit** [comment]
> Is anything needed beyond the version bump in Github?

Just a little time, to wait for MELPA to poll GitHub.  That's happened now.  Thanks!
